//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaEscuela.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alumno()
        {
            this.alu_pro = new HashSet<alu_pro>();
            this.mat_alu1 = new HashSet<mat_alu>();
        }
    
        public int mat_alu { get; set; }
        public string nom_alu { get; set; }
        public Nullable<int> edad_alu { get; set; }
        public Nullable<int> sem_alu { get; set; }
        public string gen_alu { get; set; }
        public Nullable<int> clave_c1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alu_pro> alu_pro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mat_alu> mat_alu1 { get; set; }
        public virtual carrera carrera { get; set; }
    }
}
