//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class alu_pro
    {
        public Nullable<int> mat_alu1 { get; set; }
        public Nullable<int> clave_p1 { get; set; }
        public int idAluProf { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
