//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class mat_alu
    {
        public int idMatAlu { get; set; }
        public Nullable<int> clave_m1To { get; set; }
        public Nullable<int> mat_alu2 { get; set; }
    
        public virtual alumno alumno { get; set; }
        public virtual materia materia { get; set; }
    }
}
