//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades.BaseD
{
    using System;
    using System.Collections.Generic;
    
    public partial class alumno
    {
        public int id_mat_alu { get; set; }
        public string nombre_alu { get; set; }
        public int edad_alu { get; set; }
        public string genero_alu { get; set; }
        public int id_carre1 { get; set; }
        public int id_mat2 { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual materia materia { get; set; }
    }
}
