//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscuelaModificadoContenx : DbContext
    {
        public EscuelaModificadoContenx()
            : base("name=EscuelaModificadoContenx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumnoes { get; set; }
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<profesor> profesors { get; set; }
    }
}
