//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class profesor
    {
        public int id_prof { get; set; }
        public string nom_p { get; set; }
        public Nullable<long> tel_p { get; set; }
        public System.DateTime hor_p { get; set; }
        public Nullable<int> id_mat1 { get; set; }
    
        public virtual materia materia { get; set; }
    }
}
